name: Playground

on:
  issue_comment:
    types: [created]

jobs:
  spitout:
    runs-on: ubuntu-18.04
    name: Check event bla
    steps:
      - name: Echo event
        run: |
          echo $GITHUB_EVENT_PATH
          jq .comment.body $GITHUB_EVENT_PATH
          cat $GITHUB_EVENT_PATH
      - name: Check if /qa was in comment
        if:  contains(github.event.issue_comment.comment.body, '/qa') != true
        run: echo Build stuff NOW
